version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: image-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongo:27017/image-labeler
    depends_on:
      - mongo

volumes:
  mongo-data:
